# this workflow deploys this repositories code to a server for demo and display.
name: deploy-workflow
run-name: Deploy RELEASE files for ${{ github.event_name }} triggered by ${{ github.triggering_actor }}
concurrency:
  group: release-deploy-files

permissions:
  contents: write
  packages: read
  actions: read

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - LICENSE.md
      - CHANGELOG.md # Should never be edited anyway
      - .git*
      - docs/**
  workflow_dispatch:

jobs:
  prepare-variables:
    runs-on: ["self-hosted", "Windows", "X64", "fcr", "deploy"]
    outputs:
      build-type: ${{ steps.get-build-type.outputs.BUILD_TYPE }}
    steps:
      - id: get-build-type
        shell: powershell
        run: |
          echo "BUILD_TYPE=RELEASE" >> $env:GITHUB_OUTPUT

  prepare-environment:
    needs: prepare-variables
    uses: ./.github/workflows/job-prepare-environment.yml

  get-version:
    needs: [prepare-variables, prepare-environment]
    uses: ./.github/workflows/job-get-version.yml
    with:
      build-type: ${{ needs.prepare-variables.outputs.build-type }}
      tag-version-prefix: ""
      version-suffix: ""

  send-files-to-server:
    needs: [prepare-variables, prepare-environment, get-version]
    uses: ./.github/workflows/job-send-files-to-server.yml
    secrets:
      SERVER_NETWORK_PATH: ${{ secrets.SERVER_NETWORK_PATH }}

  tag-repo:
    needs: [prepare-variables, get-version, send-files-to-server]
    uses: ./.github/workflows/job-tag-repo.yml
    with:
      tag-string: v${{ needs.get-version.outputs.NEXT_VERSION_NUMBER }}
      build-type: ${{ needs.prepare-variables.outputs.build-type }}

  create-release:
    needs: [prepare-variables, get-version, tag-repo]
    uses: ./.github/workflows/job-create-private-release.yml
    with:
      tag-string: v${{ needs.get-version.outputs.NEXT_VERSION_NUMBER }}
      build-type: ${{ needs.prepare-variables.outputs.build-type }}
      version-string: ${{ needs.get-version.outputs.NEXT_VERSION_NUMBER }}
