# this workflow deploys this repositories code to a server for demo and display.
name: deploy-stage
run-name: Deploy ${{ inputs.deploy-type }} images for ${{ github.event_name }} triggered by ${{ github.triggering_actor }}
concurrency:
  group: ${{ inputs.deploy-type }}-deploy-images

permissions:
  contents: read
  packages: read
  actions: read

env:
  node-version: "20"
  site-tag-prefix: "site-v"

on:
  workflow_dispatch:
    inputs:
      deploy-type:
        description: "Deploy type (release or stage)"
        required: true
        default: "stage"
        type: choice
        options:
          - release
          - stage

jobs:
  setup:
    runs-on: ubuntu-latest
