name: send-files-to-server

on:
  workflow_call:

jobs:
  send-files-to-server:
    if: ${{ success() }}
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      # copy the application files to the web server
      - name: Copy the files to the Web Server
        id: copy-files-to-server
        shell: powershell
        run: |
          robocopy "${{ github.workspace }}\App_Data\database" "${{ secrets.SERVER_NETWORK_PATH }}\App_Data\database" /E /XN /XO /XC
          robocopy "${{ github.workspace }}\App_Data\inc_files" "${{ secrets.SERVER_NETWORK_PATH }}\App_Data\inc_files" /MIR
          robocopy "${{ github.workspace }}\asp_files" "${{ secrets.SERVER_NETWORK_PATH }}\asp_files" /MIR
          robocopy "${{ github.workspace }}\images" "${{ secrets.SERVER_NETWORK_PATH }}\images" /MIR
          robocopy "${{ github.workspace }}\styles" "${{ secrets.SERVER_NETWORK_PATH }}\styles" /MIR
          robocopy "${{ github.workspace }}\Default.asp" "${{ secrets.SERVER_NETWORK_PATH }}\Default.asp"

      # just need to update the web.config file to force the server to reload the application
      - name: reboot the web server
        id: reboot-web-server
        shell: powershell
        run: |
          $webConfigPath = "${{ secrets.SERVER_NETWORK_PATH }}\web.config"
          (Get-Content $webConfigPath) | ForEach-Object { $_ -replace '(<add key="LastUpdated" value=")[^"]*(" />)', "`$1$(Get-Date -Format 'yyyy-MM-ddTHH:mm:ss')`$2" } | Set-Content $webConfigPath
